### ISSUE TITLE
Rails 3 Compatibility

### ISSUE THREAD

**Issue by logicaltext** [juliocesar/rack-pagespeed#1]
Rails 3 (beta 4) crashed (for me) when using rack-bundle. I think this is because the `Rack::Bundle#parse!` method assumes that the Body of the Rack response is an Array of Strings, but in Rails it's actually an instance of ActionDispatch::Response. The [Rack spec](http://rack.rubyforge.org/doc/files/SPEC.html) states that the body of a Rack response simply must yield Strings and respond to `each`, so Rack::Bundle#parse! should probably assume the same. Here is a [small patch](http://github.com/logicaltext/rack-bundle/commit/8e7d0282b05b01a0cbfa59b519242046437605f6) that fixes the issue.

**Comment by juliocesar** [comment]
Thanks! Much appreciated. I'll write a spec for that then look into your patch ASAP.

**Comment by logicaltext** [comment]
Sure! I was thinking about writing a spec myself, but wasn't sure how to go about it. One could certainly write something along the lines of "@response.should_receive(:each)", but maybe that's too implementation-specific?

**Comment by juliocesar** [comment]
That would be very Rack specific, but that's fine. Though now that I think about it, I don't think that spec would make sense along the lines of explaining what the program does. People using rack-bundle should safely assume it's Rack compliant right, so we don't need a spec to say that.

I'll just incorporate your patch, because it relies on the response responding to :each, which is what should be, as opposed to :join.

Thanks a lot!

**Comment by logicaltext** [comment]
> ...I don't think that spec would make sense along the lines of explaining what the program does. People using rack-bundle should safely assume it's Rack compliant right, so we don't need a spec to say that.

I completely agree.

Thanks for incorporating the patch, and thanks for a great piece of middleware! I only wish I had discovered it last week before attempting to write a similar gem (based on [Github's approach to asset bundling](http://github.com/blog/551-optimizing-asset-bundling-and-serving-with-rails)) that included view helpers in addition to a piece of middleware. But after seeing rack-bundle, I'm even more convinced that small, clean, modular pieces of Rack middleware are the way to go!

Thanks again.
