### ISSUE TITLE
Dependency on memcached

### ISSUE THREAD

**Issue by mcollina** [juliocesar/rack-pagespeed#10]
The gem depends on memcached, even if it's just a configuration option.
The memcached gem contains some native code, and that requires installing some binary package.

I think the gem should not depend on memcached, because it's not needed in the base use case.

**Comment by juliocesar** [comment]
Yeah, alright, I suppose that upon trying to use memory store, I could then request the gem.

It's just that it's not a big deal for most people (and wasn't for me at the time I wrote the gem), but I suppose it's not a bad design decision. Are you having problems getting it installed right now? If so, I'll make the change and push. If it's a suggestion, I'll keep it for when I do any further work on it.

Let me know!

**Comment by mcollina** [comment]
Well, I've branched and done it myself in a very fast way, so there's no need to hurry up :).

**Comment by mcollina** [comment]
I've closed the bug, but I didn't intend to :/. I pushed the wrong button.

**Comment by juliocesar** [comment]
I suppose forking and removing is also an option  :)

But thanks for pointing out. Hope it works well for you.

**Comment by apersaud** [comment]
First of all, thanks for the great work on the gem! Fantastic!

+1, even the edge version on git would not deploy on Heroku Cedar stack. I'll probably will have to fork and modify too - the only problem is that it increases slug size and maintenance instead of having a central place for the gem to be in.

**Comment by juliocesar** [comment]
Thank you!

I'm aware it won't deploy. And I apologise, but given how little time I've had recently to work on this, you're on your own for now.

I'll get around to fix this sometime soon.
