### ISSUE TITLE
Confusing how requires_store works

### ISSUE THREAD

**Issue by plindberg** [juliocesar/rack-pagespeed#12]
I have spent quite a while trying to determine why javascripts weren't combined.

It turned out I had not given a store directive in the configuration (because I misread the documentation, thinking that :disk was the default). But what happens then is that the filter simply isn't added to @config.filters, but the "combine_javascripts" directive is silently accepted. 

Perhaps the filter should be rejected from the available_filters array a store directive is missing. Then the startup would abort, saying the filter isn't available. Or something like that.

**Comment by juliocesar** [comment]
It should raise an exception when trying to call a filter without store specified. I'll be doing some work today on it and I'll look into that.

**Comment by juliocesar** [comment]
closed by 2a21df417c074b62bfbb8410d735c823a207b9d7

**Comment by juliocesar** [comment]
Fixed. Run gem install again to fetch 1.0.4. Though I assume you've sorted out the problem on your side already.

Thanks!

**Comment by plindberg** [comment]
Great, thanks!
