### ISSUE TITLE
Rack version

### ISSUE THREAD

**Issue by sxua** [juliocesar/rack-pagespeed#14]
I have a rack 1.2.2 (oa-oauth depends on it), but rack-pagespeed works only with 1.2.1.

**Comment by juliocesar** [comment]
Noted. Though in fact it will work with ~ 1.2. The problem is that the Gemfile.lock requires specifically 1.2.1.

I'll keep this open until the next release, but if you want the fix ASAP, edit the Gemfile.lock and change it to the version you have.

**Comment by sxua** [comment]
Sure, it's not a problem to fix, but it's better to install it with less actions :)
