### ISSUE TITLE
minify_javascript should have an exclude flag

### ISSUE THREAD

**Issue by mcollina** [juliocesar/rack-pagespeed#15]
This is more a feature request than a bug, but I think is needed.

Currently minify_javascript is a global on-off feature, I could not selectively minify only some of my javascript files.
I would not try to minify jquery for example, as I'm wasting cpu and response time.

**Comment by juliocesar** [comment]
I personally never keep a minified library at development time, and if I may make a suggestion, I'd recommend you against it, as reading the source is invaluable. That includes jQuery or whatever else.

I think this has to do with your specific case of having a lot of JS to minify, correct? If I recall from the other issue, you went with compression at deploy time, which I agree with in cases where the load of JS is significant.

I'll leave this one out for now. If there's more push for it, I'll look into it again. Thanks!

**Comment by mcollina** [comment]
I agree with you, but I will prefer using the minified version from the library (i.e. jquery, or sencha touch) project rather than using the one built with the tool as it may give better results in term of compressions. 
To achieve this I tipically use a somewhat old-fashioned if to manage my libraries :). If we are in production I include the minified ones, while on development I include the unminified. 

Really, with big JS library its way better to minify them at deploy time. I'm building an extremely simple rake task: https://github.com/mcollina/rake-minify.
