### ISSUE TITLE
Perhaps make redis, memcached etc optional?

### ISSUE THREAD

**Issue by plindberg** [juliocesar/rack-pagespeed#20]
I’m not sure it’s a good idea to have rack-pagespeed depend on memcached, redis etc. I think you should place them within the :test group so people can explicitly add them to their Gemfiles if they use those stores.

On Heroku, the recommendation is to not have a “slug size” greater than 40M (impacts performance when handling dynos in their mesh). And every explicit dependency adds to this slug size. So it’s not good to have extra weight you don’t use.

**Comment by plindberg** [comment]
(Also, the gemspec isn’t updated with the redis dependency.)

**Comment by DAddYE** [comment]
+1

**Comment by juliocesar** [comment]
I can't put it in a `:test` group as the gem will be only available to people running tests. But I see your point, and I agree with it.

I'll come up with a different loader for storage today when I do some work on it.

**Comment by juliocesar** [comment]
Release 1.0.6. Redis and Memcached are now only required upon calling the corresponding store. Thanks.
