### ISSUE TITLE
Page ends being clipped

### ISSUE THREAD

**Issue by brandonweiss** [juliocesar/rack-pagespeed#23]
This is a weird bug; I'm not even sure exactly how to describe it. I'm using rack-pagespeed with Sinatra, and my views are being partially clipped at the bottom. There's no real consistency to it. I mean, if I reload, the same amount of data will be clipped. But if I alter the amount of data in the view (more data, less data), sometimes even just the last few tags will be clipped, or maybe even the entire footer. I don't know if this is relevant, but it's also not evenly clipped. So sometimes it'll cut off in the middle of tags.

It took me a while to identify this is a rack-pagespeed bug, but eventually I tried commenting out this block:

```
use Rack::PageSpeed, :public => "#{Minimalog.settings.root}/public" do
  store :memcached
  combine_css
end
```

And the problem went away. Any idea what might be wrong?

**Comment by juliocesar** [comment]
Hey,

happy to look into it for you. I need the exact version of Ruby you're using, down to the patch level, so I can try and replicate it.

Thanks.

**Comment by brandonweiss** [comment]
Thanks! Here's what I'm using:

```
ruby 1.9.2p136 (2010-12-25 revision 30365) [x86_64-darwin10.6.0]
```

**Comment by brandonweiss** [comment]
Also, I just upgraded to `ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-darwin10.7.0]` and I'm still having the same problem.

**Comment by juliocesar** [comment]
Closing this as I cannot replicate the problem no matter what.
