### ISSUE TITLE
Not working, but no error either on Rails 

### ISSUE THREAD

**Issue by brandonweiss** [juliocesar/rack-pagespeed#24]
Well, I'm just having awful luck. I tried it out on a Rails app and couldn't get it to work at all. Here's what I did.

```
# Gemfile
gem 'rack-pagespeed', :require => 'rack/pagespeed'

# config/application.rb
module CleverAppName
  class Application < Rails::Application
    config.middleware.use Rack::PageSpeed, :public => Rails.public_path do
      store :disk => Dir.tmpdir # require 'tmpdir'
      combine_css
    end
  end
end
```

It doesn't throw an error, but it also doesn't run any of the filters either. At least as far as I can tell.

**Comment by brandonweiss** [comment]
Oh, I should add that I'm using `ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-darwin10.7.0]`, and I tried it out on another app and got the same results, just in case it was somehow app-specific.

**Comment by juliocesar** [comment]
That is weird. I can't replicate none if the issues you reported, using exactly the same version of Ruby you are.

I'm suspecting it could be a conflicting version of Rack, but rack-pagespeed does force ~>1.2, which as the test suite shows, it's safe.

Sorry man  :/

P.S.: it's a move of desperation, but try removing the `:require` statement from the Gemfile. It's designed so you won't need that.

**Comment by brandonweiss** [comment]
Hrm, just tried that but it didn't fix it. The bizarre thing is it doesn't appear to be app-specific or system-specific. I started a brand new Rails app to test it with and it didn't work. I even deployed to Heroku (my actual app and the test app), and neither worked.

**Comment by brandonweiss** [comment]
But then it does work on Sinatra, but with an error (the page end clipping). And that also happens when deployed to Heroku.

I can't figure out what the connection is other. I would have said 1.9.2, but I just tried it with 1.8.7 and I still can't get the filters to run.

**Comment by juliocesar** [comment]
What version of Rails? I'll give it one more go, but I'm running rack-pagespeed latest on a whole bunch of apps. Specs are passing, including on 1.9.2-p180.

**Comment by brandonweiss** [comment]
I've tried it on both 3.0.5 and 3.0.7.

**Comment by juliocesar** [comment]
I've ran a new Rails 3.0.7 app with it, on 1.9.2-p180. The only conflict was with Rack 1.2.2 (Rails), and rack-pagespeed (1.2.1). I solved it by running `bundle update`. So yeah, I was wrong in that I thought I hadn't specified an exact Rack version, but anyway, the problem you described didn't happen.

One thing though: `combine_css` will only act if if finds neighbouring stylesheets in the app. Meaning, you need to have more than one stylesheet link tag, and they need to come one after another in the HTML, or the filter will ignore it.

Same goes for `combine_javascripts`.

**Comment by brandonweiss** [comment]
Damn, for a sec I thought that might have been it, but I do have two stylesheets one after each other in the layout. I don't suppose you have a dummy/test app you could send me? One that you know works that I could try running?

**Comment by juliocesar** [comment]
Sure. Email me at julio@awesomebydesign.com and I'll reply to you.

Steps I took:
- `rvm install 1.9.2-p180 && rvm gemset create rpsbug`
- Activated both
- `gem install rails rack-pagespeed`
- `rails new foo`
- Copied the `config.middleware.use` use as above
- Added a dummy stylesheet to `public/stylesheets` with 1 attribute in it.
- `rails g scaffold book`
- Ran the server, went to `/books`, checked the output HTML, works fine.

**Comment by brandonweiss** [comment]
Well shit. On a totally bare app I can get it working now. I'll start playing around with it; trying to figure out what's different between this one and the other two apps.

**Comment by brandonweiss** [comment]
Progress! OK, the first issue is maybe with rendering actions without layouts? The page that I was refreshing to test it but apparently couldn't get rack-pagespeed to work on is a landing page, so the it looks different but really didn't need a whole separate layout, so we just put all the HTML in that action's view file and render false for layout.

But then again, I'm not sure why that would matter, since you're just parsing the response with Nokogiri, right?

**Comment by juliocesar** [comment]
`But then again, I'm not sure why that would matter, since you're just parsing the response with Nokogiri, right?`

Correct. rack-pagespeed doesn't care where the response comes from. By the time it sees a response, it's completely out of the framework, if you're using it as indicated above.

Dunno!
