### ISSUE TITLE
@import stylesheet paths

### ISSUE THREAD

**Issue by brandonweiss** [juliocesar/rack-pagespeed#25]
So if I've got a stylesheet with something like this. 

```
@import url("reset.css");
@import url("master.css");
```

This will load `reset` and `master` in relative to the current stylesheet, which is also in the `public/stylesheets` dir. But with rack-pagespeed on it looks like it's trying to load them at the root, e.g. `/reset.css` and `/master.css`, and then throwing a 404. Or in my case worse, because I've got a catch-all route for usernames (e.g. `/brandonweiss`).

**Comment by juliocesar** [comment]
rack-pagespeed wasn't built with `@import` statements in mind, so I'm not surprised to hear it doesn't work.

My suggestion is: get rid of them, and keep those inline in the HTML document.

Or disable the CSS filters altogether.

**Comment by brandonweiss** [comment]
Oh I agree, @import is no good, I've already taken them out; a person I was working with put them in there. I just wanted to note it in case it was unintentional.
