### ISSUE TITLE
Rack dependency 1.2.1 still present in HEAD

### ISSUE THREAD

**Issue by swrobel** [juliocesar/rack-pagespeed#28]
The Rack 1.2.1 dependency is still specified in Gemfile.lock and the gemspec file. Please fix and avoid hardcoding to specific versions in the future.

**Comment by juliocesar** [comment]
No it's not. Check the `Gemfile` on `master`.

But I assume you mean in the _gem_, right? It's there because I haven't taken the time yet to merge / do a bunch of changes in it. But feel free to fork/fix.

**Comment by swrobel** [comment]
No, try including this in your Gemfile:
gem "rack-pagespeed", :git => "git://github.com/juliocesar/rack-pagespeed.git"
It will still try to use 1.2.1. I forked and fixed, although I'm not certain I did it properly. It complains about not being able to require dalli. See my fork of your repo.

**Comment by swrobel** [comment]
I'm not a gem developer, but this seems like a useful resource on how to clear up the conflicts you have in terms of the Gemfile, Gemfile.lock and gemspec: http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

**Comment by juliocesar** [comment]
I am aware of the issue (and how to fix it). See previous bug reports.

I haven't had the time to work on it. Until I do, the solution is fork/fix.
