### ISSUE TITLE
Wrapping all responses in HTML 

### ISSUE THREAD

**Issue by josh803316** [juliocesar/rack-pagespeed#37]
Not sure why but as soon as I enable this library all responses from Ajax calls that are expecting json are getting wrapped in HTML doctype wrappers. Any ideas why this might happen?

**Comment by juliocesar** [comment]
Ensure your API responses are being issued with the correct `Content-Type` header. rack-pagespeed [inspects that](https://github.com/juliocesar/rack-pagespeed/blob/master/lib/rack/pagespeed.rb#L27) in order to determine whether it should do anything with it or not.

**Comment by josh803316** [comment]
Thanks it was an issue with our app not  setting the right Content-Type
