### ISSUE TITLE
no such file to load -- md5

### ISSUE THREAD

**Issue by stevenkolstad** [juliocesar/rack-pagespeed#4]
no such file to load -- md5

This error occurred while loading the following files:
   /Users/agentrock/.rvm/gems/ruby-1.9.2-head/gems/rack-bundle-0.2.3/lib/rack/bundle/bundles/base
   md5

**Comment by juliocesar** [comment]
MD5 is part if Ruby's standard lib. What might be going on there is you compiled your Ruby without MD5, either by explicitly disabling it or some other way.

**Comment by stevenkolstad** [comment]
Weird, I just did rvm install 1.9.2.

Oh, just googled it.

There are md5 changes between ruby 1.8 and 1.9. "require 'md5'" works on 1.8 but not 1.9--it needs to be "require 'digest/md5'"

**Comment by juliocesar** [comment]
Right, suits me well for not looking into it more carefully.

The fix is as easy as wrapping this in a begin / rescue block. I'll add it in later on today. Thanks a lot for the report!

**Comment by stevenkolstad** [comment]
No problem,

Thanks for the fix!
