### ISSUE TITLE
Make it possible to use different JS Minifying libraries?

### ISSUE THREAD

**Issue by clintecker** [juliocesar/rack-pagespeed#6]
I see you're using JSMin which is a bit long in the tooth and quite conservative.  Some people like UglifyJS, Closure Compiler, or YUI Compressor.  

It would be nice if you could use whatever minifier you like.

**Comment by juliocesar** [comment]
When I wrote that filter, I actually went for Google Closure first through the closure-compiler gem, and then ruby-yui-compressor. Both require Java (not the problem), and upon compressing any JavaScript, there's a 1-2 seconds delay between calling the compress method and getting the output, which would be prohibitive for a tool that compresses JS on the fly such as rack-pagespeed.

So unless it's Ruby or C based (read: near instant execution), the performance hit would be too high. I'm happy to help you write a filter that uses those gems though if you need it!

**Comment by juliocesar** [comment]
P.S.: UglifyJS requires node.js as I understand it. Not sure how that will play with getting the gem to seamlessly install on platforms like Heroku. I'll look into it, possibly make it an option. We'll see.
