### ISSUE TITLE
Default Name

### ISSUE THREAD

**Issue by DAddYE** [juliocesar/rack-pagespeed#9]
Very interesting project. The only big problem for me is that all files are named <code>rack-pagespeed-*</code> I need to customize <code>rack-pagespeed</code>. It's possible?

**Comment by juliocesar** [comment]
Thanks!

There's no configuration parameter for that, which means you can fork the project, change the value, make a gem, and use your fork for that.

**Comment by DAddYE** [comment]
Yep, but it's not a great idea fork and keep every thing updated with your repo, is a big deal for you make it as an option?

**Comment by juliocesar** [comment]
I'll keep the issue open for future reference when I do more work on it. It's not something that I see as a major issue (as in, it's not preventing anything from working).

**Comment by DAddYE** [comment]
yep sure is only a small enhancement. Thanks!
